### ISSUE TITLE
AugerHole Broken

### ISSUE THREAD

**Issue by kr15h** [rcolyer/threads-scad#4]
Thank you! One of the best libraries I have used lately.

I was trying AugerHole with the following code and it does create an AugerThread instead. Using OpenSCAD 2019.05
 on Ubuntu 20.04.2 LTS.
```
AugerHole(outer_diam = 30, inner_diam = 25, 
  height = 20, pitch = 2, 
  position=[0,0,0], rotation=[0,0,0], 
  tooth_angle=30, tolerance=0.4){
    cylinder(d = 40, h = 15);
  }
```
![threads_test](https://user-images.githubusercontent.com/817241/132123309-b63ce977-3766-4f9c-837a-ec20ba27acb8.png)

**Comment by rcolyer** [comment]
Yes, you're right.  AugerHole needed a children().  This works now, as long as you choose a valid pitch.  2 was too small for an auger thread of those parameters.
```
AugerHole(outer_diam = 30, inner_diam = 25,
  height = 20, pitch = 5,
  position=[0,0,-1], rotation=[0,0,0],
  tooth_angle=30, tolerance=0.4){
    cylinder(d = 40, h = 15);
  }
```
