### ISSUE TITLE
Can't create a partially threaded screwhole

### ISSUE THREAD

**Issue by alidaf** [rcolyer/threads-scad#6]
This may be purely down to usage such as the sequence of applying the screwhole module and removing the unthreaded part. I've tried multiple permutations but every time I print out the parts, the screw reaches the thread and will not engage. I've been successful with fully threaded parts but cannot get a partially threaded to work. Could you please add an example to the demo? I am forcing the thread pitch to 2mm, which I think forces the thread height to the same.

**Comment by rcolyer** [comment]
The described problem is unclear to me, as I don't know what "partially threaded" or "unthreaded part" means here.  Can you provide an example of what's failing?

**Comment by alidaf** [comment]
I posted this a while ago but IIRC the partially threaded part I was trying to describe is a shaft where only the last part is threaded. I was using a bolt that had a small section of shaft adjacent to the head where the diameter was >= the thread OD. I think the part where the thread starts left a small solid section where the diameter is the same as the thread OD so there is no "entrance" to the thread, which is why the bolt wouldn't engage. It was one of my first projects with SCAD and as I said, it may be down to the sequence of removal or not using a "safe" removal method, i.e. removing a part that is slightly larger so it doesn't leave a zero thickness wall. I don't have the model files and don't use the library any more so it's moot and I'll close the issue.
